version: '3'
volumes:
  db:
services:
  server:
    restart: on-failure
    image: ghcr.io/bluepython508/habits:master
    env_file: .env
    environment:
      - "ROCKET_DB_URL=postgres://postgres:postgres@db/postgres"
    ports:
      - "8080:80"
  db:
    image: postgres:14
    env_file: .env
    volumes:
      - db:/var/lib/postgresql/data