version: '3'
volumes:
  db:
services:
  server:
    build: .
    env_file: .env
    environment:
      - "ROCKET_DB_URL=postgres://postgres:postgres@db/postgres"
    ports:
      - "8080:80"
  db:
    image: postgres:14
    env_file: .env
    volumes:
      - db:/var/lib/postgresql/data